//this variable will hold a random number generated by the random() function
long randomNumber;
String a = ": "; 

bool complete = true; 
bool done = false; 

//Set up - this is where you get things "set-up". It will only run once
void setup() {
  
  //setup serial communications through the USB
  Serial.begin(9600);

  //Let's make it more random
 // randomSeed(42);   
      
}//close setup

void loop() {
  
  // //generate a random number
  // randomNumber = random(0,50);
  
  // //display the random number on the serial monitor
  // Serial.print("The Random Number is = ");
  // Serial.println(randomNumber);
  if (complete){
    for (int i = 1; i <= 50; i = i + 1) {
      randomNumber = random(0,50);    
      Serial.println(i + a + randomNumber) ;
    }
    complete = false; 
  }
  
}